stages:
  - test
  - demo
  - docs

default:
  interruptible: true

variables:
  TRANSFER_METER_FREQUENCY: "2s"
  ARTIFACT_COMPRESSION_LEVEL: "fast"

workflow:
  rules:
    - if: $CI_PIPELINE_SOURCE == 'merge_request_event'
    - if: $CI_COMMIT_TAG
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH

test:
  stage: test
  trigger:
    include: tests/tests.gitlab-ci.yml
    strategy: depend
  rules:
    - changes:
      - $CI_PROJECT_DIR/algorithms/*.h
      - $CI_PROJECT_DIR/data_structures/*.h
      - $CI_PROJECT_DIR/tests/*
      - $CI_PROJECT_DIR/gitlab-ci.yml

demo:
  stage: demo
  trigger:
    include: demos/demos.gitlab-ci.yml
    strategy: depend
  needs:
    - test
  rules:
    - changes:
      - $CI_PROJECT_DIR/algorithms/*.h
      - $CI_PROJECT_DIR/data_structures/*.h
      - $CI_PROJECT_DIR/demos/**/*
      - $CI_PROJECT_DIR/.gitlab-ci.yml

docs:
  stage: docs
  image: debian:buster-slim
  script:
    - apt-get update && apt-get install -y
      build-essential
      cmake
      doxygen
      libboost-all-dev
    - mkdir build
    - cd build
    - cmake ..
    - make docs
  rules:
    - changes:
      - $CI_PROJECT_DIR/algorithms/*.h
      - $CI_PROJECT_DIR/data_structures/*.h
      - $CI_PROJECT_DIR/Doxyfile
      - $CI_PROJECT_DIR/CMakeLists.txt
  tags:
    - docker 
