stages:
  - build
  - test

build_cmake:
  image: amardikian/clang-3.8
  stage: build
  script:
    - mkdir build
    - cd build
    - cmake ..
  tags:
    - shared-fi


building_tests:
  image: gcc:latest
  stage: test
  script:
    - make
  tags:
    - shared-fi
  dependencies:
    - build_cmake

